<a href="https://colab.research.google.com/github/taeilkeemm/fordatastudy/blob/main/%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%A7%88%EC%9D%B4%EB%8B%9D_%ED%80%B4%EC%A6%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones((3, 5), dtype='float64')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
##1)

arra1 = np.floor(((np.random.random(10)*10))+1)
arra1

array([5., 1., 7., 3., 9., 2., 3., 3., 2., 9.])

In [22]:
arra2 = np.floor((np.random.random(12)*10)+1).reshape(3,4)
arra2

array([[10.,  7.,  2.,  7.],
       [ 3., 10.,  5.,  9.],
       [ 7.,  7.,  1.,  1.]])

In [23]:
arra3 = np.floor((np.random.random(36)*10)+1).reshape(3,3,4)
arra3

array([[[10.,  5.,  5.,  5.],
        [ 4.,  5.,  4.,  2.],
        [ 6.,  2.,  7.,  9.]],

       [[ 1., 10.,  2.,  2.],
        [10.,  7., 10.,  4.],
        [ 5.,  2., 10.,  9.]],

       [[ 4.,  2.,  2.,  8.],
        [ 7.,  3.,  4., 10.],
        [ 4.,  5.,  1.,  2.]]])

In [24]:
arra1[1::2]

array([1., 3., 2., 3., 9.])

In [25]:
arra2[:,1::2]

array([[ 7.,  7.],
       [10.,  9.],
       [ 7.,  1.]])

In [26]:
arra2[::-1,::-1]

array([[ 1.,  1.,  7.,  7.],
       [ 9.,  5., 10.,  3.],
       [ 7.,  2.,  7., 10.]])

In [27]:
np.maximum(arra2, arra3[[1]])

array([[[10., 10.,  2.,  7.],
        [10., 10., 10.,  9.],
        [ 7.,  7., 10.,  9.]]])